### ISSUE TITLE
Teste Front/Back-end

### ISSUE THREAD

**Issue by felipe-ssilva** [grupoboticario/testepraticodevs#1]
Oi pessoal,

Aqui para o e-comm em SP, estamos aplicando os seguintes testes: https://github.com/felipe-ssilva/challenge

Acreditam que possa ser aproveitado/reaproveitado? Podemos inserir o teste no canal https://github.com/grupoboticario?

Para back-end, ainda estamos criando um desafio em node.js. Devemos finalizá-lo até a próxima semana.

**Comment by JessiiPer** [comment]
Olá! Gostaria de saber um pouco mais dessa API externa (https://mdaqk8ek5j.execute-api.us-east-1.amazonaws.com/v1/cashback?cpf=12312312323)  que foi disponibilizado para consumo da minha rota get.
Foi passado um token de acesso para ser usado no header... mas não precisou. Se entrar nesse link você já consegue o retorno da API. É isso mesmo?

**Comment by felipe-ssilva** [comment]
@JessiiPer sugiro abrir uma nova issue.

@brunopenso @BrunoPensoGB pode ajudá-la? Após, irei excluir essa issue que criei.

**Comment by brunopenso** [comment]
@JessiiPer isso mesmo. A Apis é um mock!!!
