### ISSUE TITLE
Dúvida no cálculo de cashback

### ISSUE THREAD

**Issue by mvibraim** [grupoboticario/testepraticodevs#4]
Pegando um critério de bonificação como exemplo:

`Para até 1.000 reais em compras, o revendedor(a) receberá 10% de cashback do valor vendido no período;`

Não foi especificado o que seria o período. Pelos critérios de bonificação, fica claro que o percentual de cashback depende de um período que não foi especificado.

Exemplo de forma de calcular, assumindo que o período é o mês das compras:

`Como o cálculo do cashback depende do valor das compras no período, deveria aguardar o término do mês, fazer o somatório das compras do mês e calcular o cashback de acordo com o valor do somatório.`

O que mais parece fazer sentido para mim é que esse período seja o mês das compras, ou seja, só seria possível calcular o cashback no final de cada mês.

Também faz sentido que o período seja o intervalo de tempo entre a primeira compra e a data de criação de uma nova compra. Nesse caso, o cashback seria calculado utilizando o valor da soma de todas as compras existentes.

**Comment by brunopenso** [comment]
Olá, você pode considerar o mês atual como referência.
