### ISSUE TITLE
Quantos são os status possíveis?

### ISSUE THREAD

**Issue by matheusmilani** [grupoboticario/testepraticodevs#5]
No desafio é dito 2 status possíveis para uma nova compra: "Em validação" e "Aprovado".
Com isso posso concluir que exista mais um status de "Reprovado".
Mas em nenhum momento isso é afirmado, e nem mesmo como é feita essa troca de status.

**Comment by brunopenso** [comment]
Matheus essas regras não estão explicitas para deixar você construir da melhor forma que acha possível. A ideia do teste não é ser uma coisa fechada, pode usar sua criatividade e vontade para fazer coisas diferentes mantendo a base do teste.
