### ISSUE TITLE
Forma de cálculo do Cashback

### ISSUE THREAD

**Issue by msuchy** [grupoboticario/testepraticodevs#8]
# Forma de cálculo do Cashback

A partir da descrição das rotas entende-se que a cada compra será aplicado um valor de cashback, conforme exemplo abaixo. Neste cenário o revendedor receberia um total de **R$ 575,00**

Cod | Valor | Data | CPF | STATUS | % cashback | valor cashback |
---- | ----- | ----- | ---- | -------- | -----------  | ---------------- |
1 | R$ 900,00 | 21/06/2020 | 012.345.678.90 | VALIDAÇÃO | 10% | R$ 90,00 |
2 | R$ 1100,00 | 21/06/2020 | 012.345.678.90 | VALIDAÇÃO | 15% | R$ 165,00 |
3 | R$ 1600,00 | 21/06/2020 | 012.345.678.90 | VALIDAÇÃO | 20% | R$ 320,00 |

No entanto, a partir da descrição dos critérios de bonificação, o cashback seria aplicado apenas ao final do período, utilizando o somatório das compras como base de calculo do percentual aplicado. Desta forma, no cenário acima, o revendedor fez um total de R$2700,00 no período, onde seria aplicado o percentual de 20% e receberia **R$ 540,00** de cashback para o próximo mês.

### Os percentuais de cashback devem ser aplicados compra a compra, ou apenas ao final do período de um mês?

**Comment by ecalgarotto** [comment]
Olá Margareth, tudo bem?
Pode considerar a aplicação do cálculo de cashback ao final do período, utilizando a soma dos valores das vendas, que é o que realmente interessa. Nesse caso, se pesquisarmos antes da virada do período, considerar a soma do valor até aquele momento e aí sim aplicar o cálculo.
